name: IG Reels Scheduler

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:         # manual run button

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scheduler
        env:
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          GRAPH_VERSION: v20.0
          MANIFEST_PATH: posts/manifest.csv
          POLL_INTERVAL_SECONDS: "8"
          POLL_TIMEOUT_SECONDS: "180"
        run: |
          python scripts/ig_reels_scheduler.py

      - name: Commit manifest changes (if any)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add posts/manifest.csv
            git commit -m "Mark posted reels [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
